### ISSUE TITLE
How do I add an item to a gui created with TexturedInventoryWrapper

### ISSUE THREAD

**Issue by Lfeier03** [LoneDev6/GUIExample#2]
How should I create a item for this gui

TexturedInventoryWrapper inventory = new TexturedInventoryWrapper(null,
                                                                          54,
                                                                          ChatColor.BLACK + "Test",
                                                                          new FontImageWrapper("minecraft:cd01")
        );
        //Is that right? It seems like a reaction.
        Inventory gui = inventory.getinventory
        gui.setTime(size , item)
        inventory.showInventory(player);

**Comment by Lfeier03** [comment]
@LoneDev6

**Comment by LoneDev6** [comment]
You should try before asking and waiting, it's pointless to wait for me. Avoid pinging.
The API docs have everything you need.

https://github.com/LoneDev6/API-ItemsAdder/blob/e77eb2c17e03c82e7ba10290204d5b0a8447a352/src/main/java/dev/lone/itemsadder/api/FontImages/TexturedInventoryWrapper.java#L254

```java
inventory.getInternal().setItem(index, item);
```
